window.SCENARIOS['generator'] = {
    meta: {
      title: "Grapple Gauntlet: Networked Grappling Hook Setup",
      description:
        "Grapple input triggers with no effect. Check Enhanced Input setup, trace hits, and replication fundamentals.",
      estimateHours: 2.2
    },
    start: "step-1",
    steps:
	{
		'step-1': {skill:'input',title:'Step 1: The Silent Grapple Input',prompt:"<p>You've set up an Enhanced Input Action for a grappling hook, but pressing the key does nothing. The <code>OnTriggered</code> event never fires.</p><strong>What is the most common reason for an Enhanced Input Action to fail at runtime?</strong>",choices:[{text:'Action: Verify the Input Mapping Context containing the action has been added to the Local Player Subsystem.',type:'correct',feedback:"<p><strong>Optimal Time Logged:</strong> Enhanced Input requires explicitly adding mapping contexts to the Player Controller’s subsystem, usually in BeginPlay.</p>",next:'step-2'},{text:'Action: Check the Input Action asset for the \"Consume Input\" flag.',type:'misguided',feedback:"<p><strong>Extended Time Logged (Investigation):</strong> Consumption affects propagation after firing, not whether the event fires in the first place.</p>",next:'step-2'},{text:'Action: Add the key binding to the Project Settings > Input section.',type:'partial',feedback:"<p><strong>Standard Time Logged:</strong> This refers to the legacy system. You should focus on the Enhanced Input setup.</p>",next:'step-2'},{text:'Action: Change the Character Movement Component to block all input.',type:'wrong',feedback:"<p><strong>Maximum Time Logged (Ineffective Fix):</strong> The movement component handles movement, not the raw input action firing.</p>",next:'step-2'}]},
		'step-2': {skill:'traces',title:'Step 2: The Trace That Misses Walls',prompt:"<p>The input fires. You line trace to find a grapple point, but the trace never hits any static geometry.</p><strong>What is the most likely cause of a complete trace failure?</strong>",choices:[{text:'Action: Inspect the Line Trace Channel to ensure world geometry is set to \"Block\" that specific trace channel.',type:'correct',feedback:"<p><strong>Optimal Time Logged:</strong> A channel mismatch (where the trace asks for Visibility, but the geometry ignores it) is the most common setup error.</p>",next:'step-3'},{text:'Action: Increase the length of the line trace to several thousand units.',type:'partial',feedback:"<p><strong>Standard Time Logged:</strong> The trace could be too short, but a collision channel issue is a more fundamental error.</p>",next:'step-3'},{text:'Action: Replace the Line Trace with a Sphere Trace for better hit detection.',type:'misguided',feedback:"<p><strong>Extended Time Logged (Investigation):</strong> Line traces work perfectly fine. Changing the trace type is unnecessary complexity.</p>",next:'step-3'},{text:'Action: Check if the trace is set to \"Ignore\" the player character.',type:'wrong',feedback:"<p><strong>Maximum Time Logged (Ineffective Fix):</strong> The trace is failing to hit the wall, not hitting the player. This is a misplaced check.</p>",next:'step-3'}]},
		'step-3': {skill:'rep',title:'Step 3: Rubber-Band Pull in Multiplayer',prompt:"<p>The grappling pull works perfectly in single-player. In a multiplayer test, clients grapple and pull forward, but then snap back to their starting position.</p><strong>What causes this classic client-server desynchronization?</strong>",choices:[{text:'Action: The movement logic (e.g., Launch Character) is executing on the client only; it must be executed inside a \"Run on Server\" RPC.',type:'correct',feedback:"<p><strong>Optimal Time Logged:</strong> Movement is server-authoritative. The client applies the move locally (prediction) but the server corrects it because it never executed the move officially.</p>",next:'step-4'},{text:'Action: The Character Movement Component has client-side prediction disabled.',type:'partial',feedback:"<p><strong>Standard Time Logged:</strong> Prediction helps feel, but the server's failure to execute the official move is the root of the snap-back.</p>",next:'step-4'},{text:'Action: The connection is too lagged, and the server is over-correcting the position.',type:'misguided',feedback:"<p><strong>Extended Time Logged (Investigation):</strong> Lag exaggerates the problem, but a non-authoritative move is the root logical error.</p>",next:'step-4'},{text:'Action: Change the movement component’s network update rate to a higher frequency.',type:'wrong',feedback:"<p><strong>Maximum Time Logged (Ineffective Fix):</strong> Increasing the update rate increases bandwidth cost without fixing the lack of server execution.</p>",next:'step-4'}]},
		'step-4': {skill:'systems',title:'Step 4: Grapple While Stunned',prompt:"<p>The player can still grapple even when they have the 'State.Stunned' Gameplay Tag applied to them. The grapple ability should be blocked by this tag.</p><strong>What is the best-practice method to block an ability based on a state tag?</strong>",choices:[{text:'Action: Implement a check at the start of the grapple logic for \"Has Tag: State.Stunned\" to gate activation.',type:'correct',feedback:"<p><strong>Optimal Time Logged:</strong> Gameplay Tags are the scalable, data-driven solution for state management and gating specific abilities.</p>",next:'step-5'},{text:'Action: Create a boolean <code>bIsStunned</code> on the character and check it before dashing.',type:'partial',feedback:"<p><strong>Standard Time Logged:</strong> This works for one state but becomes unmanageable as the number of states (rooted, silenced, etc.) grows. Tags are the cleaner solution.</p>",next:'step-5'},{text:'Action: Disable player input entirely when the stun debuff is applied.',type:'misguided',feedback:"<p><strong>Extended Time Logged (Investigation):</strong> This is a sledgehammer approach that also blocks camera rotation and menu access, which may not be desired.</p>",next:'step-5'},{text:'Action: Use the <code>Disable Character Movement</code> node during the stun effect.',type:'wrong',feedback:"<p><strong>Maximum Time Logged (Ineffective Fix):</strong> Disabling movement does not disable input actions like the grapple input event itself.</p>",next:'step-5'}]},
		'step-5': {skill:'animation',title:'Step 5: Animation Snaps In/Out',prompt:"<p>The grapple fire animation montage plays, but it snaps instantly from the idle pose and snaps instantly back, creating a jarring look.</p><strong>What controls the smooth transition into and out of a montage?</strong>",choices:[{text:'Action: Adjust the Blend In and Blend Out time properties within the Anim Montage asset itself.',type:'correct',feedback:"<p><strong>Optimal Time Logged:</strong> The Montage asset's settings directly control the interpolation duration between the base pose and the montage pose.</p>",next:'conclusion'},{text:'Action: Increase the Character Movement Component\'s \"Ground Friction\" setting.',type:'partial',feedback:"<p><strong>Standard Time Logged:</strong> Friction affects movement stop, not animation blending smoothness.</p>",next:'conclusion'},{text:'Action: Use a custom Blend Profile in the AnimBP AnimGraph.',type:'misguided',feedback:"<p><strong>Extended Time Logged (Investigation):</strong> Blend Profiles control skeletal weighting during the blend, but Blend In/Out Time controls the duration of the transition.</p>",next:'conclusion'},{text:'Action: Set the montage play rate to 0.5.',type:'wrong',feedback:"<p><strong>Maximum Time Logged (Ineffective Fix):</strong> Play rate affects speed, not transition smoothness.</p>",next:'conclusion'}]}
	}

  };