window.SCENARIOS['terminal'] = {
    meta: {
      title: "Lighting Overhaul: Scene Appears Incorrect After Setup",
      description:
        "Scene lighting appears inconsistent—some areas are overexposed or dark, reflections outdated, and post-process effects not applying.",
      estimateHours: 1.8
    },
    start: "step-1",
    steps:
      {
        'step-1': {skill:'lighting',title:'Step 1: The Dark Scene After Build',prompt:"<p>Your level appears completely dark after adding static/stationary lights and rebuilding. The lights are visible in the viewport but not at runtime.</p><strong>What is the most likely cause?</strong>",choices:[{text:'Action: Lighting needs to be rebuilt; the lighting build failed or was interrupted.',type:'correct',feedback:"<p><strong>Optimal Time Logged:</strong> Static and stationary lights require a lighting build to bake lightmaps and visibility data. Without a successful build, baked lighting will not render properly.</p>",next:'step-2'},{text:'Action: The Post Process Volume\'s exposure settings are set too low.',type:'partial',feedback:"<p><strong>Standard Time Logged:</strong> Low exposure darkens the scene, but complete darkness is usually a sign of unbuilt/failed baked lighting.</p>",next:'step-2'},{text:'Action: Lumen is disabled in the project settings.',type:'misguided',feedback:"<p><strong>Extended Time Logged (Investigation):</strong> Even without Lumen, static or stationary lights still render with built lighting data.</p>",next:'step-2'},{text:'Action: The Directional Light component is accidentally hidden in-game.',type:'wrong',feedback:"<p><strong>Maximum Time Logged (Ineffective Fix):</strong> Hiding the light does not affect the baked lightmaps, which is the source of light for static meshes.</p>",next:'step-2'}]},
        'step-2': {skill:'lighting',title:'Step 2: The Overexposed Room',prompt:"<p>After rebuilding lighting, the interior looks washed out, blown out, and too bright.</p><strong>What is the best initial check to manage scene brightness consistently?</strong>",choices:[{text:'Action: Verify and clamp the auto exposure settings (Min/Max Brightness) in the Post Process Volume.',type:'correct',feedback:"<p><strong>Optimal Time Logged:</strong> Auto exposure dynamically adjusts brightness. Clamping min/max values provides consistent and manageable lighting.</p>",next:'step-3'},{text:'Action: Decrease the intensity of all lights in the scene by half.',type:'partial',feedback:"<p><strong>Standard Time Logged:</strong> This is a temporary, non-systematic fix. The correct solution is managing the final camera exposure.</p>",next:'step-3'},{text:'Action: Disable Bloom in the Post Process Volume.',type:'misguided',feedback:"<p><strong>Extended Time Logged (Investigation):</strong> Bloom adds a glow effect; it does not cause the core overexposure issue.</p>",next:'step-3'},{text:'Action: Switch the Directional Light\'s mobility to Movable.',type:'wrong',feedback:"<p><strong>Maximum Time Logged (Ineffective Fix):</strong> Light mobility settings do not fix camera exposure problems.</p>",next:'step-3'}]},
        'step-3': {skill:'rendering',title:'Step 3: Reflection Probes Not Updating',prompt:"<p>Reflection capture probes are placed, but metallic surfaces reflect outdated or incorrect images, even after scene changes.</p><strong>Why are the reflection captures not refreshing their cubemaps?</strong>",choices:[{text:'Action: Manually recapture the reflections using the "Update Captures" button on the Reflection Capture component or in the main toolbar.',type:'correct',feedback:"<p><strong>Optimal Time Logged:</strong> Reflection captures are static and must be manually updated after geometry or lighting changes to refresh the cubemaps.</p>",next:'step-4'},{text:'Action: Increase the bounds of the Lightmass Importance Volume.',type:'partial',feedback:"<p><strong>Standard Time Logged:</strong> This affects baked lighting quality, not the capture of reflection cubemaps.</p>",next:'step-4'},{text:'Action: Switch from static Reflection Captures to Screen Space Reflections (SSR).',type:'misguided',feedback:"<p><strong>Extended Time Logged (Investigation):</strong> This trades a capture quality issue for a screen-space artifact issue, solving the problem with a new problem.</p>",next:'step-4'},{text:'Action: Change the Reflection Capture component\'s mobility to Movable.',type:'wrong',feedback:"<p><strong>Maximum Time Logged (Ineffective Fix):</strong> Reflection Captures are inherently static and do not have a mobility setting.</p>",next:'step-4'}]},
        'step-4': {skill:'lighting',title:'Step 4: Light Bleeding Through Walls',prompt:"<p>Bright baked light is visibly leaking through the corners and seams of interior walls, especially where meshes meet.</p><strong>What is the primary cause and solution for light bleeding with baked lighting?</strong>",choices:[{text:'Action: Increase the UV padding (distance between UV islands) in the lightmap UV channel of the mesh to prevent bleeding across map edges.',type:'correct',feedback:"<p><strong>Optimal Time Logged:</strong> Lightmap bleeding occurs when UV islands are too close, allowing light from one side of a surface to bleed onto another. Padding is the direct fix.</p>",next:'step-5'},{text:'Action: Lower the overall intensity of the SkyLight.',type:'partial',feedback:"<p><strong>Standard Time Logged:</strong> This reduces the severity of the bleed but does not fix the root UV problem in the asset geometry.</p>",next:'step-5'},{text:'Action: Increase the Lightmap Resolution on the mesh.',type:'misguided',feedback:"<p><strong>Extended Time Logged (Investigation):</strong> Higher resolution can sometimes exaggerate bleeding if the padding is poor.</p>",next:'step-5'},{text:'Action: Change the material blend mode to Masked to prevent light transmission.',type:'wrong',feedback:"<p><strong>Maximum Time Logged (Ineffective Fix):</strong> Material blend modes do not affect how lightmaps are generated or how light bleeds through baked data.</p>",next:'step-5'}]},
        'step-5': {skill:'rendering',title:'Step 5: Black Reflections on Glass',prompt:"<p>A translucent material, such as glass, is rendering as completely black instead of reflecting the environment.</p><strong>What is the limitation causing this effect, and what is the typical workaround?</strong>",choices:[{text:'Action: Translucent materials do not support Lumen Reflections or SSR; switch the material to use Planar Reflections or screen-space effects.',type:'correct',feedback:"<p><strong>Optimal Time Logged:</strong> This is a known rendering limitation. Translucent surfaces must use specific, often expensive, reflection techniques (Planar) or SSR/Lumen must be disabled for them.</p>",next:'conclusion'},{text:'Action: Set the material\'s Roughness value to 1.0 to increase reflection quality.',type:'partial',feedback:"<p><strong>Standard Time Logged:</strong> Roughness affects clarity, not the core problem of the reflection being black or missing due to rendering pipeline limitations.</p>",next:'conclusion'},{text:'Action: Enable the "Cast Dynamic Shadows" flag on the glass mesh.',type:'misguided',feedback:"<p><strong>Extended Time Logged (Investigation):</strong> Shadows are unrelated to reflection capture and rendering on translucent surfaces.</p>",next:'conclusion'},{text:'Action: Increase the Post Process Volume\'s reflection blend weight.',type:'wrong',feedback:"<p><strong>Maximum Time Logged (Ineffective Fix):</strong> The component blend weight affects the mix, but the reflection data itself is missing/black due to a pipeline limitation.</p>",next:'conclusion'}]}
      }
  };