const TRANSLATIONS = {
    'en': {
        'app.title': 'UE5 Scenario Tracker',
        'timer.remaining': 'Time Remaining',
        'debug.mode': 'Debug Mode',
        'admin.tools': 'Admin Tools',
        'btn.clear_cache': 'Clear Cache & Restart',
        'backlog.title': 'Sprint Backlog',
        'ticket.placeholder.title': 'Select a ticket',
        'ticket.placeholder.desc': 'Choose a ticket from the backlog on the left to get started.',
        'status.completed': 'COMPLETED',
        'status.in_progress': 'IN PROGRESS',
        'status.not_started': 'NOT STARTED',
        'label.logged': 'Logged:',
        'label.est': 'Est:',
        'label.est_time': 'Est. Time:',
        'modal.times_up': "Time's Up!",
        'modal.incomplete': "The assessment period has ended. Assessment incomplete.",
        'modal.complete': "Assessment Complete!",
        'modal.complete_sub': "You have completed all assigned tickets.",
        'btn.copy_key': 'Copy Key',
        'btn.copied': 'Copied!',
        'difficulty.short': 'SHORT',
        'difficulty.med': 'MED',
        'difficulty.long': 'LONG',
        'category.ai': 'AI',
        'category.assets': 'Assets',
        'category.audio': 'Audio',
        'category.blueprint': 'Blueprint',
        'category.blueprints': 'Blueprints',
        'category.cinematics': 'Cinematics',
        'category.core': 'Core',
        'category.gameplay': 'Gameplay',
        'category.general': 'General',
        'category.lighting': 'Lighting',
        'category.materials': 'Materials',
        'category.nanite': 'Nanite',
        'category.performance': 'Performance',
        'category.physics': 'Physics',
        'category.post_process': 'Post Process',
        'category.postprocess': 'PostProcess',
        'category.procedural': 'Procedural',
        'category.rendering': 'Rendering',
        'category.tools': 'Tools',
        'category.ui': 'UI',
        'category.volumetrics': 'Volumetrics',
        'category.world': 'World',
        'category.world_building': 'World Building'
    },
    'es': {
        'app.title': 'Rastreador de Escenarios UE5',
        'timer.remaining': 'Tiempo Restante',
        'debug.mode': 'Modo Depuración',
        'admin.tools': 'Herramientas de Admin',
        'btn.clear_cache': 'Borrar Caché y Reiniciar',
        'backlog.title': 'Backlog del Sprint',
        'ticket.placeholder.title': 'Selecciona un ticket',
        'ticket.placeholder.desc': 'Elige un ticket del backlog a la izquierda para comenzar.',
        'status.completed': 'COMPLETADO',
        'status.in_progress': 'EN PROGRESO',
        'status.not_started': 'NO INICIADO',
        'label.logged': 'Registrado:',
        'label.est': 'Est:',
        'label.est_time': 'Tiempo Est:',
        'modal.times_up': "¡Se acabó el tiempo!",
        'modal.incomplete': "El período de evaluación ha terminado. Evaluación incompleta.",
        'modal.complete': "¡Evaluación Completa!",
        'modal.complete_sub': "Has completado todos los tickets asignados.",
        'btn.copy_key': 'Copiar Clave',
        'btn.copied': '¡Copiado!',
        'difficulty.short': 'CORTO',
        'difficulty.med': 'MEDIO',
        'difficulty.long': 'LARGO',
        'category.audio': 'Audio',
        'category.blueprint': 'Blueprint',
        'category.gameplay': 'Jugabilidad',
        'category.lighting': 'Iluminación',
        'category.tools': 'Herramientas',
        'category.ui': 'Interfaz',
        'category.rendering': 'Renderizado',
        'category.post_process': 'Post-procesado',
        'category.core': 'Núcleo',
        'category.world_building': 'Construcción de Mundos',
        'category.general': 'General'
    },
    'zh': {
        'app.title': 'UE5 场景追踪器',
        'timer.remaining': '剩余时间',
        'debug.mode': '调试模式',
        'admin.tools': '管理工具',
        'btn.clear_cache': '清除缓存并重启',
        'backlog.title': '冲刺待办列表',
        'ticket.placeholder.title': '选择一个工单',
        'ticket.placeholder.desc': '从左侧的待办列表中选择一个工单以开始。',
        'status.completed': '已完成',
        'status.in_progress': '进行中',
        'status.not_started': '未开始',
        'label.logged': '已记录:',
        'label.est': '预估:',
        'label.est_time': '预估时间:',
        'modal.times_up': "时间到！",
        'modal.incomplete': "评估期已结束。评估未完成。",
        'modal.complete': "评估完成！",
        'modal.complete_sub': "您已完成所有分配的工单。",
        'btn.copy_key': '复制密钥',
        'btn.copied': '已复制！',
        'difficulty.short': '短',
        'difficulty.med': '中',
        'difficulty.long': '长',
        'category.audio': '音频',
        'category.blueprint': '蓝图',
        'category.gameplay': '游戏玩法',
        'category.lighting': '光照',
        'category.tools': '工具',
        'category.ui': '界面',
        'category.rendering': '渲染',
        'category.post_process': '后期处理',
        'category.core': '核心',
        'category.world_building': '世界构建',
        'category.general': '通用'
    },
    'ko': {
        'app.title': 'UE5 시나리오 트래커',
        'timer.remaining': '남은 시간',
        'debug.mode': '디버그 모드',
        'admin.tools': '관리자 도구',
        'btn.clear_cache': '캐시 지우기 및 다시 시작',
        'backlog.title': '스프린트 백로그',
        'ticket.placeholder.title': '티켓 선택',
        'ticket.placeholder.desc': '왼쪽의 백로그에서 티켓을 선택하여 시작하세요.',
        'status.completed': '완료됨',
        'status.in_progress': '진행 중',
        'status.not_started': '시작 안 함',
        'label.logged': '기록됨:',
        'label.est': '예상:',
        'label.est_time': '예상 시간:',
        'modal.times_up': "시간 종료!",
        'modal.incomplete': "평가 기간이 종료되었습니다. 평가 미완료.",
        'modal.complete': "평가 완료!",
        'modal.complete_sub': "할당된 모든 티켓을 완료했습니다.",
        'btn.copy_key': '키 복사',
        'btn.copied': '복사됨!',
        'difficulty.short': '짧음',
        'difficulty.med': '중간',
        'difficulty.long': '김',
        'category.audio': '오디오',
        'category.blueprint': '블루프린트',
        'category.gameplay': '게임플레이',
        'category.lighting': '라이팅',
        'category.tools': '도구',
        'category.ui': 'UI',
        'category.rendering': '렌더링',
        'category.post_process': '포스트 프로세스',
        'category.core': '코어',
        'category.world_building': '월드 빌딩',
        'category.general': '일반'
    },
    'ja': {
        'app.title': 'UE5 シナリオトラッカー',
        'timer.remaining': '残り時間',
        'debug.mode': 'デバッグモード',
        'admin.tools': '管理ツール',
        'btn.clear_cache': 'キャッシュをクリアして再起動',
        'backlog.title': 'スプリントバックログ',
        'ticket.placeholder.title': 'チケットを選択',
        'ticket.placeholder.desc': '左側のバックログからチケットを選択して開始してください。',
        'status.completed': '完了',
        'status.in_progress': '進行中',
        'status.not_started': '未着手',
        'label.logged': '記録:',
        'label.est': '見積:',
        'label.est_time': '見積時間:',
        'modal.times_up': "時間切れ！",
        'modal.incomplete': "評価期間が終了しました。評価は未完了です。",
        'modal.complete': "評価完了！",
        'modal.complete_sub': "割り当てられたすべてのチケットを完了しました。",
        'btn.copy_key': 'キーをコピー',
        'btn.copied': 'コピーしました！',
        'difficulty.short': '短',
        'difficulty.med': '中',
        'difficulty.long': '長',
        'category.audio': 'オーディオ',
        'category.blueprint': 'ブループリント',
        'category.gameplay': 'ゲームプレイ',
        'category.lighting': 'ライティング',
        'category.tools': 'ツール',
        'category.ui': 'UI',
        'category.rendering': 'レンダリング',
        'category.post_process': 'ポストプロセス',
        'category.core': 'コア',
        'category.world_building': 'ワールド構築',
        'category.general': '一般'
    }
};

let currentLanguage = localStorage.getItem('ue5_language') || 'en';

function t(key) {
    if (!TRANSLATIONS[currentLanguage]) return key;
    return TRANSLATIONS[currentLanguage][key] || key;
}

function setLanguage(lang) {
    if (TRANSLATIONS[lang]) {
        currentLanguage = lang;
        localStorage.setItem('ue5_language', lang);
        updateStaticTranslations();
        // Dispatch event for other scripts to react
        document.dispatchEvent(new CustomEvent('languageChanged', { detail: { language: lang } }));
    }
}

function updateStaticTranslations() {
    document.querySelectorAll('[data-i18n]').forEach(element => {
        const key = element.getAttribute('data-i18n');
        element.textContent = t(key);
    });
}

// Initialize static text on load
document.addEventListener('DOMContentLoaded', () => {
    updateStaticTranslations();
});
